version: "3.8"

services:
  redis:
    image: redis:6.2
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    ports:
      - "6379:6379"

  echoserver:
    build: ./echoserver
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
    volumes:
      - ./echoserver:/app # Монтируем локальную директорию с кодом внутрь контейнера
    command: /bin/sh -c "npm install && nodemon index.js"
