services:
  redis:
    image: redis:6.2
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  echoserver:
    build: ./echoserver
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGUSER=your_db_user
      - PGPASSWORD=your_db_password
      - PGDATABASE=your_db_name
      - PGPORT=5432
    ports:
      - "3000:3000"
    volumes:
      - ./echoserver:/app # Монтируем локальную директорию с кодом внутрь контейнера
    command: /bin/sh -c "npm install && nodemon index.js"

volumes:
  pgdata:
